services: 
  db:
    image: mysql:8.0
    container_name: myapp-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: ghcr.io/reiserfs/mypod/mypod-php:v${APP_VERSION}
    container_name: myapp-app
    restart: unless-stopped
    env_file: .env
    volumes:
      - app_code:/var/www/html
      - ./.env:/var/www/html/.env 
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: myapp-nginx
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf.d:/etc/nginx/conf.d:ro
      - app_code:/var/www/html:ro
    depends_on:
      - app

volumes:
  db_data:
  app_code: