name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar QEMU
        uses: docker/setup-qemu-action@v3

      - name: Configurar Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login no GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extrair versão da tag
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # Build da imagem base apenas se houver mudanças ou commit "build-custom-php"
      - name: Verificar se precisa buildar base
        id: check_base
        run: |
          if git log -1 --pretty=%B | grep -q "build-custom-php"; then
            echo "BUILD_BASE=true" >> $GITHUB_ENV
          elif git diff --quiet HEAD^ HEAD -- docker/Dockerfile.base; then
            echo "BUILD_BASE=false" >> $GITHUB_ENV
          else
            echo "BUILD_BASE=true" >> $GITHUB_ENV
          fi

      - name: Build & Push base image
        if: env.BUILD_BASE == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.base
          push: true
          tags: ghcr.io/${{ github.repository }}/custom-8.4-fpm-alpine:latest
          platforms: linux/amd64,linux/arm64

      # Build da imagem final da aplicação
      - name: Build & Push app image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.app
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/mypod-php:${{ env.VERSION }}
            ghcr.io/${{ github.repository }}/mypod-php:latest
          platforms: linux/amd64,linux/arm64
