name: Main

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Criar release semântico
        uses: go-semantic-release/action@v1
        with:
          provider: github-token
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
