name: Main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Semantic Versioning Release
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/go-semantic-release/semantic-release:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Release Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release --token "${GITHUB_TOKEN}"          
